
language: python
python:
- '3.6'
matrix:
  include:
  - os: linux
    env: MBED_CLOUD=1.5.0 ARMGCC_VERSION=6.3.1
before_install:
- pip install -U pip wheel
- pip install mbed-cli
- mbed deploy
- mbed new .
- chmod +x mbed-ci/toolchain_install.sh
- . mbed-ci/toolchain_install.sh && linux_default_download
script:
- mbed cache on
- mbed update
- mbed config GCC_ARM_PATH $HOME/bin
- mkdir -p BUILD

